#!/bin/sh

ACTIVE_PROFILES=$1
ODPT_API_TOKEN=$2
ODPT_API_ENDPOINT=$3

cat <<EOF > app.yaml
runtime: java11

instance_class: F1

env_variables:
    SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILES}
    NET_UONEWEB_TOKYOTRAINNOW_ODPTAPI_KEY: ${ODPT_API_TOKEN}
    NET_UONEWEB_TOKYOTRAINNOW_ENDPOINT: ${ODPT_API_ENDPOINT}
EOF

