name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: gradle build

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deployment-artifacts
          path: build/libs

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Download deployment artifacts
        uses: actions/download-artifact@v2
        with:
          name: deployment-artifacts
          path: build/libs

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          working_directory: ${{ github.workspace }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
